# :----------------------------------------------------------------------- INFO
# :[share/ael-files/ael-files.toml]
# :author        : alterEGO Linux
# :created       : 2025-06-11 01:03:28 UTC
# :updated       : 2025-06-11 01:03:41 UTC
# :description   : AEL files.

[bin.YnVzeQ==]
filename    = "/bin/busy"
description = "When the boss comes around to look busy."

[shellutils.c25ha2UtZW52]
filename    = "/shellutils/snake-env"
description = "Manage python -m venv."

[shellutils.utils.YXJndW1lbnQtcGFyc2Vy]
filename    = "/shellutils/utils/argument-parser"
description = "Argument parser utility."
