# :: --------------------------------------------------------------------- INFO
# :: [share/ael-files/ael-files.toml]
# :: author        : alterEGO Linux
# :: created       : 2025-06-11 01:03:28 UTC
# :: updated       : 2025-08-24 15:12:03 UTC
# :: description   : AEL files.

[bin.YnVzeQ==]
filename    = "/bin/busy"
description = "When the boss comes around to look busy."

[shellutils.ZGVsZXRl]
filename    = "/shellutils/delete"
description = "Delete directories."

[shellutils.ZGVlcC1ubWFw]
filename    = "/shellutils/deep-nmap"
description = "Deep Nmap scan."

[shellutils.ZGVlcC1zY2Fu]
filename    = "/shellutils/deep-scan"
description = "Scans IP with rustscan and nmap."

[shellutils.ZGlyZWN0b3J5LXNpemU=]
filename    = "/shellutils/directory-size"
description = "Check size of biggest directories."

[shellutils.ZWxldmF0ZQ==]
filename    = "/shellutils/elevate"
description = "Repeats last command with sudo, if forgotten."

[shellutils.ZXh0cmFjdG9y]
filename    = "/shellutils/extractor"
description = "Compressed files universal extractor."

[shellutils.Z2V0bXAz]
filename    = "/shellutils/getmp3"
description = "Extracting audio (.mp3) from video."

[shellutils.Z290bw==]
filename    = "/shellutils/goto"
description = "Simple directory bookmarks system."

[shellutils.aXNwZWVk]
filename    = "/shellutils/ispeed"
description = "Internet connection speed meter."

[shellutils.cGFjbWFuLXJlc2V0]
filename    = "/shellutils/pacman-reset"
description = "Re-initialize pacman sync, mirrorlist and keyring."

[shellutils.cG9ydHM=]
filename    = "/shellutils/ports"
description = "Displays open ports."

[shellutils.cHJvY2Vzc2Vz]
filename    = "/shellutils/processes"
description = "Show processes."

[shellutils.cHMtZ3JlcA==]
filename    = "/shellutils/ps-grep"
description = "Show processes for a particular application."

[shellutils.cHktY2xlYW5lcg==]
filename    = "/shellutils/py-cleaner"
description = "Clean python current directory."

[shellutils.cHktc2VydmVy]
filename    = "/shellutils/py-server"
description = "Create a Python HTTP server."

[shellutils.cmVzZXQtdGltZQ==]
filename    = "/shellutils/reset-time"
description = "Reset system time. Useful when Windows boot screws time."

[shellutils.c2hlbGwtaW5mbw==]
filename    = "/shellutils/shell-info"
description = "Show shell info."

[shellutils.c2hvdy11dGM=]
filename    = "/shellutils/show-utc"
description = "Show UTC time."

[shellutils.c25ha2UtZW52]
filename    = "/shellutils/snake-env"
description = "Manage python -m venv."

[shellutils.dGVybWJpbg==]
filename    = "/shellutils/termbin"
description = "Netcat-based command-line pastebin."

[shellutils.dG11eHBsdXM=]
filename    = "shellutils/tmuxplus"
description = "TMUX wrapper."

[shellutils.d2hvaXN3ZWI=]
filename    = "/shellutils/whoisweb"
description = "Query WHOIS web if <whois> port 43 is blocked on your network."

[shellutils.utils.YWVsLWZ6Zg==]
filename    = "/shellutils/utils/ael-fzf"
description = "FZF wrapper."

[shellutils.utils.YXJndW1lbnQtcGFyc2Vy]
filename    = "/shellutils/utils/argument-parser"
description = "Argument parser utility."
