# :----------------------------------------------------------------------- INFO
# :[share/ael-files/ael.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2025-01-09 11:44:30 UTC
# :updated       : 2025-01-09 11:44:34 UTC
# :description   : Configuration file.
