# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael/files.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-22 20:35:16 UTC
# :updated       : 2024-09-26 17:35:31 UTC
# :description   : List of files.

[root.files]
filename    = "files.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/files.toml"
dst         = "/usr/share/ael/files.toml"
description = "AEL files list."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[root.firefox]
filename    = "firefox.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/firefox.toml"
dst         = "/usr/share/ael/firefox.toml"
description = "Firefox config."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[root.packages]
filename    = "packages.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/packages.toml"
dst         = "/usr/share/ael/packages.toml"
description = "Packages config."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[root.shellutils]
filename    = "shellutils.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/shellutils.toml"
dst         = "/usr/share/ael/shellutils.toml"
description = "AEL Shell utils."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[dockerfiles.Dockerfile-kali]
filename    = "Dockerfile-kali"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/dockerfiles/Dockerfile-kali"
dst         = "/usr/share/ael/dockerfiles/Dockerfile-kali"
description = "Kali Linux Dockerfile."
modes       = []
is_symlink  = true
create_bkp  = false
