# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael/files.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-22 20:35:16 UTC
# :updated       : 2024-09-26 17:35:31 UTC
# :description   : List of files.

[config.files]
filename    = "files.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/files.toml"
dst         = "/usr/share/ael/files.toml"
description = "AEL files list."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[config.firefox]
filename    = "firefox.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/usr/share/ael-config/firefox.toml"
src         = "ael-files/usr/share/ael-config/"
dst         = "/usr/local/share/ael-config/firefox.toml"
description = "Firefox config."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[config.packages]
filename    = "packages.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/usr/share/ael-config/packages.toml"
src         = "ael-files/usr/share/ael-config/"
dst         = "/usr/local/share/ael-config/packages.toml"
description = "Packages config."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[config.shellutils]
filename    = "shellutils.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/usr/share/ael-config/shellutils.toml"
src         = "ael-files/usr/share/ael-config/"
dst         = "/usr/local/share/ael-config/shellutils.toml"
description = "AEL Shell utils."
modes       = ['base']
is_symlink  = true
create_bkp  = false

[dockerfiles.Dockerfile-kali]
filename    = "Dockerfile-kali"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/usr/share/ael-dockerfiles/Dockerfile-kali"
src         = "ael-files/usr/share/ael-dockerfiles/"
dst         = "/usr/local/share/ael-dockerfiles/Dockerfile-kali"
description = "Kali Linux Dockerfile."
modes       = []
is_symlink  = true
create_bkp  = false
