# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael/files.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-22 20:35:16 UTC
# :updated       : 2024-09-26 17:35:31 UTC
# :description   : List of files.

[root--files]
filename    = "files.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/files.toml"
src         = "/usr/share/ael/files.toml"
dst         = "/usr/share/ael/files.toml"
description = "AEL files list."
modes       = ['base']
requires    = []
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []

[root--firefox]
filename    = "firefox.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/firefox.toml"
src         = "/usr/share/ael/firefox.toml"
dst         = "/usr/share/ael/firefox.toml"
description = "Firefox config."
modes       = ['base']
requires    = []
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []

[root--packages]
filename    = "packages.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/packages.toml"
src         = "/usr/share/ael/packages.toml"
dst         = "/usr/share/ael/packages.toml"
description = "Packages config."
modes       = ['base']
requires    = []
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []

[root--shellutils]
filename    = "shellutils.toml"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/shellutils.toml"
src         = "/usr/share/ael/shellutils.toml"
dst         = "/usr/share/ael/shellutils.toml"
description = "AEL Shell utils."
modes       = ['base']
requires    = []
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []

[dockerfiles--Dockerfile-kali]
filename    = "Dockerfile-kali"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/dockerfiles/Dockerfile-kali"
src         = "/usr/share/ael/dockerfiles/Dockerfile-kali"
dst         = "/usr/share/ael/dockerfiles/Dockerfile-kali"
description = "Kali Linux Dockerfile."
modes       = []
requires    = []
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []

[shellutils--busy]
filename    = "busy"
url         = "https://raw.githubusercontent.com/alterEGO-Linux/ael-files/main/shellutils/busy"
src         = "/usr/share/ael/shellutils/busy"
dst         = "$HOME/.ael/shellutils/busy"
description = "When the boss comes around to look busy."
modes       = []
requires    = ['pkg/coreutils(cat)',
               'pkg/grep',
               'pkg/util-linux(hexdump)']
optional    = []
is_symlink  = true
create_bkp  = false
notes       = []
