#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/lazygit]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-01 19:55:12 UTC
# :updated       : 2024-09-19 17:11:56 UTC
# :description   : Updating GIT repo when you are lazy.

# :/Add local git repositories to update in ~/.ael/.extra in the variable
# : LAZYGIT.
[ -f ${HOME}/.ael/.extra ] && . ${HOME}/.ael/.extra

lazygit() {

    echo "================================================================================"
    echo "[+] lazygit()"
    echo "    Updating GIT repo when you are lazy."
    echo "================================================================================"
    echo

    if [[ ! -e "${LAZYGIT}" ]]; then
        echo "[!] NO repository found."
        echo "[!] Add reposiroties to LAZYGIT array in ~/.ael/.extra."
        echo "[!] Example:"
        echo "      LAZYGIT=("
        echo "               \"\${HOME}/repo/repo1\""
        echo "               \"\${HOME}/repo/repo2\""
        echo "               \"\${HOME}/repo/repo3\""
        echo "               \"\${HOME}/repo/repo4\""
        echo "              )"
    else
        _cwd="$(pwd)"
        cd ${HOME}
        for repo in "${LAZYGIT[@]}"; do
            echo "[-] Updating $repo"
            cd "$repo"
            command git pull \
            && command git add . \
            && command git commit -m "Updated using lazygit..." \
            && command git push
            echo
            cd ${HOME}
        done
        cd "$_cwd"
    fi
    }
