#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/ps-grep]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:56:31 UTC
# :updated       : 2024-09-16 12:19:13 UTC
# :description   : Show processes for a particular application.

ps-grep() {

    echo "================================================================================"
    echo "[+] ps-grep()"
    echo "    Running <ps aux | grep -Ei \"^USER.*COMMAND|[${1:0:1}]${@#?}\" | grep --color=always -E \"[${1:0:1}]${@#?}|$\">."
    echo "    Show processes for a particular application."
    echo "================================================================================"
    echo

    command ps aux \
    | command grep -Ei "^USER.*COMMAND|[${1:0:1}]${@#?}" \
    | command grep --color=always -E "[${1:0:1}]${@#?}|$"
  }
