#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/show-utc]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 01:36:14 UTC
# :updated       : 2024-09-16 15:48:01 UTC
# :description   : Show UTC time.

show-utc() {

    echo "================================================================================"
    echo "[+] show-utc()"
    echo "    Show UTC time."
    echo "================================================================================"
    echo

    echo $(command date --utc "+%F %H:%M:%S %Z")
    }
