#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/snake-vault]
# :author        : fantomH @alterEGO Linux
# :created       : 2024-09-20 12:04:49 UTC
# :updated       : 2024-09-20 12:04:53 UTC
# :description   : Simple Python environment manager.

snake-vault() {

    echo "================================================================================"
    echo "[+] snake-vault"
    echo "    Simple Python environment manager."
    echo "================================================================================"
    echo

    # :/Creating a minimal Jupyter notebook.
    echo '{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}'

  }
