#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/termbin]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-26 17:45:44 UTC
# :updated       : 2024-09-16 17:43:59 UTC
# :description   : Netcat-based command-line pastebin.

  # :/url/ https://termbin.com/
  # :usage `echo just testing! | termbin`

  alias termbin="command nc termbin.com 9999"
