#! /usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [shellutils/utils/check-applications]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2025-12-22 12:14:50 UTC
# updated       : 2025-12-28 21:04:37 UTC
# description   : Function to check applications' availability.

[ -n "${__SOURCED_CHECK_APPLICATIONS:-}" ] && return
__SOURCED_CHECK_APPLICATIONS=1

check-applications() {

    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'
    local app
    local apps=("$@")
    local missing=()

    for app in "${apps[@]}"; do
        if ! command -v "${app}" > /dev/null 2>&1; then
            missing+=("${app}")
        fi
    done

    if (( ${#missing[@]} > 0 )); then

        for app in "${missing[@]}"; do
            printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."

            local __converter="${HOME}/.ael/bin/convert-toml-json.py"
            local __packages="${HOME}/.local/share/ael-files/ael-packages.toml"
            if [ -e "${__converter}" ] && [ -f "${__packages}"  ]; then
                mapfile -t pkgs < <(
                    python "$__converter" "$__packages" |
                    jq -r --arg app "$app" '
                      to_entries[]
                      | select( ((.value.included_app? // []) | any(.[]; endswith("/" + $app))) )
                      | .key
                    '
                )
            else
                mapfile -t pkgs < <(
                    $finder $finder_args -- "/usr/bin/${app}" 2>/dev/null | sort -u
                )
            fi

            # --- fallback, search by name.
            if (( ${#pkgs[@]} == 0 )); then
                mapfile -t pkgs < <(
                    $finder $finder_args -- "${app}" 2>/dev/null | sort -u
                )
            fi

            if (( ${#pkgs[@]} > 0 )); then
                printf '%s[*]%s %s is part of %s%s%s\n' "${BLUE}" "${RESET}" "${app}" "${BLUE}" "${pkgs[0]}" "${RESET}"
            else
                printf '%s\n' "${RED}[!]${RESET} Could not find the package owning ${app}."
            fi
        done
    return 1
    fi
}
