## ----------------------------------------------------------------------- INFO
## [/usr/share/ael/files.toml]
## author        : fantomH @alterEGO Linux
## created       : 2023-11-22 20:35:16 UTC
## updated       : 2024-01-01 04:22:01 UTC
## description   : List of files.

[file.files]
filename    = "files.toml"
category    = "config"
src         = "FILESGIT"
dst         = "/usr/share/ael"
description = "AEL files list."
mode        = ['hacker']
is_symlink  = true
create_bkp  = false

[file.packages]
filename    = "packages.toml"
category    = "config"
src         = "FILESGIT"
dst         = "/usr/share/ael"
description = "Packages list."
mode        = ['hacker']
is_symlink  = true
create_bkp  = false

## ---------- [ /etc/ ] 

[file.issue]
filename    = "issue"
category    = "etc"
src         = "FILESGIT"
dst         = "/etc"
description = "Prelogin message."
mode        = ['hacker']
is_symlink  = false
create_bkp  = false

## (* /etc/skel *)

[file.alacritty]
filename    = "alacritty.toml"
category    = "config"
src         = "FILESGIT"
dst         = "/etc/skel/.config/alacritty"
description = "Alacritty configuration file."
mode        = ['hacker', 'hacker-hyprland']
is_symlink  = true
create_bkp  = false

[file.hyprland]

[file.waybar_config]
filename    = "config.jsonc"
category    = "config"
src         = "FILESGIT"
dst         = "/etc/skel/.config/waybar"
description = "Waybar configuration files."
mode        = ['hyprland']
is_symlink  = false
create_bkp  = false

[file.waybar_style]
filename    = "style.css"
category    = "config"
src         = "FILESGIT"
dst         = "/etc/skel/.config/waybar"
description = "Waybar CSS file."
mode        = ['hyprland']
is_symlink  = false
create_bkp  = false

## ---------- [ /lib/ ]

[file.ff-policies]
filename    = "policies.json"
category    = "firefox"
src         = "FILESGIT"
dst         = "/lib/firefox/distribution"
description = "Firefox global config."
mode        = ['hacker']
is_symlink  = false
create_bkp  = false

## ---------- [ /usr/lib/ ] 

[file.os-release]
filename    = "os-release"
category    = "usr-lib"
src         = "FILESGIT"
dst         = "/usr/lib"
description = "OS identification data."
mode        = ['hacker']
is_symlink  = false
create_bkp  = false

## ---------- [ /usr/share/ ] 

# vim: foldmethod=marker
## ------------------------------------------------------------- FIN ¯\_(ツ)_/¯
