## ----------------------------------------------------------------------- INFO
## [/usr/share/ael/files.toml]
## author        : fantomH @alterEGO Linux
## created       : 2023-11-22 20:35:16 UTC
## updated       : 2024-02-15 15:24:17 UTC
## description   : List of files.

[file.files]
filename    = "files.toml"
category    = "config"
src         = "AELFILES_LOCAL/usr/share/ael"
dst         = "/usr/share/ael/files.toml"
description = "AEL files list."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.packages]
filename    = "packages.toml"
category    = "config"
src         = "AELFILES_LOCAL/usr/share/ael"
dst         = "/usr/share/ael/packages.toml"
description = "Packages list."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

## ---------- [ /etc/ ] 

[file.issue]
filename    = "issue"
category    = "etc"
src         = "AELFILES_LOCAL/etc"
dst         = "/etc/issue"
description = "Prelogin message."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

## ---------- [ /etc/skel/ ] 

## (* tmux *)

[file.tmux]
filename    = ".tmux.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.tmux.conf"
description = "Tmux configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

## (* x11 *)

[file.xinit]
filename    = ".xinitrc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.xinitrc"
description = "X11 configuration file."
modes       = ['i3wm']
is_symlink  = false
create_bkp  = true

## ---------- [ /etc/skel/.config ] 

## (* alacritty *)

[file.alacritty]
filename    = "alacritty.toml"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/alacritty"
dst         = "/etc/skel/.config/alacritty/alacritty.toml"
description = "Alacritty configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

## (* hyprland *)

[file.hyprland]
filename    = "hyprland.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/hypr"
dst         = "/etc/skel/.config/hypr/hyprland.conf"
description = "Hyprland configuration file."
modes       = ["hyprland"]
is_symlink  = false
create_bkp  = true

## (* i3 *)

[file.i3]
filename    = "config"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/i3"
dst         = "/etc/skel/.config/i3/config"
description = "i3wm configuration file."
modes       = ["i3wm"]
is_symlink  = false
create_bkp  = true

## (* i3blocks *)

[file.i3blocks]
filename    = "i3blocks.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/i3blocks"
dst         = "/etc/skel/.config/i3blocks/i3blocks.conf"
description = "i3blocks configuration file."
modes       = ["i3wm"]
is_symlink  = false
create_bkp  = true

## (* waybar *)

[file.waybar_config]
filename    = "config.jsonc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/waybar"
dst         = "/etc/skel/.config/waybar/config.jsonc"
description = "Waybar configuration files."
modes       = ['hyprland']
is_symlink  = false
create_bkp  = true

[file.waybar_style]
filename    = "style.css"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/waybar"
dst         = "/etc/skel/.config/waybar/style.css"
description = "Waybar CSS file."
modes        = ['hyprland']
is_symlink  = false
create_bkp  = true

## ---------- [ /lib/ ]

[file.ff-policies]
filename    = "policies.json"
category    = "firefox"
src         = "AELFILES_LOCAL/lib/firefox/distribution"
dst         = "/lib/firefox/distribution/policies.json"
description = "Firefox global config."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

## ---------- [ /usr/lib/ ] 

[file.os-release]
filename    = "os-release"
category    = "usr-lib"
src         = "AELFILES_LOCAL/usr/lib"
dst         = "/usr/lib/os-release"
description = "OS identification data."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

## ---------- [ /usr/share/ ] 

# vim: foldmethod=marker
## ------------------------------------------------------------- FIN ¯\_(ツ)_/¯
