## ----------------------------------------------------------------------- INFO
## [/usr/share/ael/files.toml]
## author        : fantomH @alterEGO Linux
## created       : 2023-11-22 20:35:16 UTC
## updated       : 2023-11-26 13:24:21 UTC
## description   : List of files.

[file.files]
filename    = "files.toml"
category    = "config"
src         = "FILESGIT"
dst         = "/usr/share/ael"
description = "AEL files list."
mode        = ['hacker']
is_symlink  = true
create_bkp  = false

[file.packages]
filename    = "packages.toml"
category    = "config"
src         = "FILESGIT"
dst         = "/usr/share/ael"
description = "Packages list."
mode        = ['hacker']
is_symlink  = true
create_bkp  = false

## ---------- [ /etc/ ] 

[file.issue]
filename    = "issue"
category    = "etc"
src         = "FILESGIT"
dst         = "/etc"
description = "Prelogin message."
mode        = ['hacker']
is_symlink  = false
create_bkp  = false

## ---------- [ /usr/lib/ ] 

[file.os-release]
filename    = "os-release"
category    = "usr-lib"
src         = "FILESGIT"
dst         = "/usr/lib"
description = "OS identification data."
mode        = ['hacker']
is_symlink  = false
create_bkp  = true

## ---------- [ /usr/share/ ] 

# vim: foldmethod=marker
## ------------------------------------------------------------- FIN ¯\_(ツ)_/¯
