# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael/files.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-22 20:35:16 UTC
# :updated       : 2024-03-23 00:15:10 UTC
# :description   : List of files.

[file.files]
filename    = "files.toml"
category    = "config"
src         = "AELFILES_LOCAL/usr/share/ael"
dst         = "/usr/share/ael/files.toml"
description = "AEL files list."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.packages]
filename    = "packages.toml"
category    = "config"
src         = "AELFILES_LOCAL/usr/share/ael"
dst         = "/usr/share/ael/packages.toml"
description = "Packages list."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /etc/ ] 

[file.issue]
filename    = "issue"
category    = "etc"
src         = "AELFILES_LOCAL/etc"
dst         = "/etc/issue"
description = "Prelogin message."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /etc/skel/ ] 

# :(* bashrc *)

[file.bashrc]
filename    = ".bashrc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.bashrc"
description = "Bash configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

# :(* profile *)

[file.profile]
filename    = ".profile"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.profile"
description = "Shell configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

# :(* tmux *)

[file.tmux]
filename    = ".tmux.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.tmux.conf"
description = "Tmux configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

# :(* vim *)

[file.vimrc]
filename    = ".vimrc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.vimrc"
description = "Tmux configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

# :(* x11 *)

[file.xinit]
filename    = ".xinitrc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/"
dst         = "/etc/skel/.xinitrc"
description = "X11 configuration file."
modes       = ['i3wm']
is_symlink  = false
create_bkp  = true

# :---------- [ /etc/skel/.ael ] 

[file.aelcore]
filename    = ".aelcore"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael"
dst         = "/etc/skel/.ael/.aelcore"
description = "AEL Shell configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.dircolors]
filename    = ".dircolors"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael"
dst         = "/etc/skel/.ael/.dircolors"
description = "Shell colors configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.tryhackme]
filename    = ".tryhackme"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael"
dst         = "/etc/skel/.ael/.tryhackme"
description = "TryHackMe configuration file and commands."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /etc/skel/.ael/.ael-menu ] 

[file.aelmenutoml]
filename    = "ael-menu.toml"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael/.ael-menu"
dst         = "/etc/skel/.ael/.ael-menu/ael-menu.toml"
description = "ael-menu configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /etc/skel/.ael/bash-ael ] 

[file.bashaelcolors]
filename    = "colors.bash"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael/bash-ael"
dst         = "/etc/skel/.ael/bash-ael/colors.bash"
description = "Colors bash-ael file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.bashaelmessages]
filename    = "messages.bash"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.ael/bash-ael"
dst         = "/etc/skel/.ael/bash-ael/messages.bash"
description = "Messages bash-ael file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /etc/skel/.config ] 

# :(* alacritty *)

[file.alacritty]
filename    = "alacritty.toml"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/alacritty"
dst         = "/etc/skel/.config/alacritty/alacritty.toml"
description = "Alacritty configuration file."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = true

# :(* hyprland *)

[file.hyprland]
filename    = "hyprland.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/hypr"
dst         = "/etc/skel/.config/hypr/hyprland.conf"
description = "Hyprland configuration file."
modes       = ["hyprland"]
is_symlink  = false
create_bkp  = true

# :(* i3 *)

[file.i3]
filename    = "config"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/i3"
dst         = "/etc/skel/.config/i3/config"
description = "i3wm configuration file."
modes       = ["i3wm"]
is_symlink  = false
create_bkp  = true

# :(* i3blocks *)

[file.i3blocks]
filename    = "i3blocks.conf"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/i3blocks"
dst         = "/etc/skel/.config/i3blocks/i3blocks.conf"
description = "i3blocks configuration file."
modes       = ["i3wm"]
is_symlink  = false
create_bkp  = true

# :(* waybar *)

[file.waybar_config]
filename    = "config.jsonc"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/waybar"
dst         = "/etc/skel/.config/waybar/config.jsonc"
description = "Waybar configuration files."
modes       = ['hyprland']
is_symlink  = false
create_bkp  = true

[file.waybar_style]
filename    = "style.css"
category    = "config"
src         = "AELFILES_LOCAL/etc/skel/.config/waybar"
dst         = "/etc/skel/.config/waybar/style.css"
description = "Waybar CSS file."
modes        = ['hyprland']
is_symlink  = false
create_bkp  = true

# :---------- [ /etc/skel/.vim ] 

# :(* colors *)

[file.vim_arstotzka]
# :https://github.com/daylerees/colour-schemes/blob/master/vim/colors/arstotzka.vim
filename    = "arstotzka.vim"
category    = "vim"
src         = "AELFILES_LOCAL/etc/skel/.vim/colors"
dst         = "/etc/skel/.vim/colors/arstotzka.vim"
description = "vim color file."
modes        = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.vim_base16]
# :https://github.com/chriskempson/base16-vim
filename    = "base16-3024.vim"
category    = "vim"
src         = "AELFILES_LOCAL/etc/skel/.vim/colors"
dst         = "/etc/skel/.vim/colors/base16-3024.vim"
description = "vim color file."
modes        = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.vim_blaquemagick]
# :https://github.com/xero/blaquemagick.vim
filename    = "blaquemagick.vim"
category    = "vim"
src         = "AELFILES_LOCAL/etc/skel/.vim/colors"
dst         = "/etc/skel/.vim/colors/base16-3024.vim"
description = "vim color file."
modes        = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.vim_iceberg]
# :https://github.com/cocopon/iceberg.vim
filename    = "iceberg.vim"
category    = "vim"
src         = "AELFILES_LOCAL/etc/skel/.vim/colors"
dst         = "/etc/skel/.vim/colors/blaquemagick.vim"
description = "vim color file."
modes        = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

[file.vim_silenthill]
## https://github.com/evilwaveforms/silenthill.vim
filename    = "silenthill.vim"
category    = "vim"
src         = "AELFILES_LOCAL/etc/skel/.vim/colors"
dst         = "/etc/skel/.vim/colors/silenthill.vim"
description = "vim color file."
modes        = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /lib/ ]

[file.ff-policies]
filename    = "policies.json"
category    = "firefox"
src         = "AELFILES_LOCAL/lib/firefox/distribution"
dst         = "/lib/firefox/distribution/policies.json"
description = "Firefox global config."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /usr/lib/ ] 

[file.os-release]
filename    = "os-release"
category    = "usr-lib"
src         = "AELFILES_LOCAL/usr/lib"
dst         = "/usr/lib/os-release"
description = "OS identification data."
modes       = ['i3wm', 'hyprland']
is_symlink  = false
create_bkp  = false

# :---------- [ /usr/share/ ] 

# :------------------------------------------------------------- FIN ¯\_(ツ)_/¯
