# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael-dockerfiles/Dockerfile-kali]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-01-22 16:58:01 UTC
# :updated       : 2024-09-18 11:48:16 UTC
# :description   : Kali Linux Docker image on AEL.

FROM kalilinux/kali-rolling:latest

# :/Install kali packages
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install kali-linux-default kali-desktop-xfce xserver-xephyr dbus-x11
RUN apt-get clean

ENV USER root
WORKDIR /root

# :/Fixing startx
RUN echo "" >> /root/.bashrc
RUN echo "function startx() {" >> /root/.bashrc
RUN echo "    if [[ -e '/tmp/.X2-lock' ]]; then" >> /root/.bashrc
RUN echo "        rm -f /tmp/.X2-lock" >> /root/.bashrc
RUN echo "    fi" >> /root/.bashrc
RUN echo "    if ! pgrep Xephyr > /dev/null; then" >> /root/.bashrc
RUN echo "        Xephyr -br -ac -noreset -screen 1280x720 :2 &" >> /root/.bashrc
RUN echo "    else" >> /root/.bashrc
RUN echo "        echo 'Xephyr already running...'" >> /root/.bashrc
RUN echo "    fi" >> /root/.bashrc
RUN echo "    service dbus restart" >> /root/.bashrc
RUN echo "    DISPLAY=:2 startxfce4 &" >> /root/.bashrc
RUN echo "    wait" >> /root/.bashrc
RUN echo "    kill \$(pgrep Xephyr)" >> /root/.bashrc
RUN echo "}" >> /root/.bashrc

# :/Close Xephyr GUI
RUN echo "" >> /root/.bashrc
RUN echo "function close-gui() {" >> /root/.bashrc
RUN echo "    kill \$(pgrep Xephyr)" >> /root/.bashrc
RUN echo "}" >> /root/.bashrc

# :/ENTRYPOINT
ENTRYPOINT ["/bin/bash"]
