# :----------------------------------------------------------------------- INFO
# :[/usr/share/ael-config/firefox.toml]
# :author        : fantomH @alterEGO Linux
# :created       : 2024-09-21 01:22:04 UTC
# :updated       : 2024-09-21 01:22:08 UTC
# :description   : Firefox.

[addon.tab-stash]
name              = 'Tab Stash'
description       = 'Easily save and organize batches of tabs as bookmarks. Clear your tabs, clear your mind. Only for Firefox.'
author            = 'Josh Berry'
id                = 'tab-stash@condordes.net'
url               = 'https://addons.mozilla.org/en-US/firefox/addon/tab-stash/'
install_url       = 'https://addons.mozilla.org/firefox/downloads/latest/tab-stash/latest.xpi'
installation_mode = 'normal_installed'

[addon.adblock-plus]
name              = 'Adblock Plus'
description       = 'Adblock Plus blocks all annoying ads, and supports websites by not blocking unobtrusive ads by default (configurable).'
author            = 'Adblock Plus'





      },
      "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/adblock-plus/latest.xpi"
      },
      "{c3c10168-4186-445c-9c5b-63f12b8e2c87}": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/cookie-editor/latest.xpi"
      },
      "CSSViewer@quantum": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/cssviewer-quantum/latest.xpi"
      },
      "foxyproxy@eric.h.jung": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/foxyproxy-standard/latest.xpi"
      },
      "{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/search_by_image/latest.xpi"
      },
      "{531906d3-e22f-4a6c-a102-8057b88a1a63}": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/single-file/latest.xpi"
      },
      "wappalyzer@crunchlabz.com": {
        "installation_mode": "normal_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/wappalyzer/latest.xpi"
