#! /usr/bin/env bash
# =============================================================================
# INFO
# =============================================================================
# [/lib/bash/applications]
# 
# Author      : Pascal Malouin (https://github.com/alterEGO-Linux)
# Created     : 2026-08-30 14:32:20 UTC
# Updated     : 2026-08-30 14:32:20 UTC
# Description : Application check.
# -----------------------------------------------------------------------------

check_applications() {

    local blue=$'\033[34m'
    local red=$'\033[31m'
    local reset=$'\033[0m'
    local app

    for app in "${@}"; do
        if ! command -v $app >/dev/null 2>&1; then
            printf '%s\n' "${red}[!]${reset} ${app} is not installed."
            return 1
        fi
    done
}
