# ------------------------------------------------------------------------ INFO
# [/.tmux.conf]
# author        : Pascal Malouin (https://github.com/alterEGO-Linux)
# created       : 2021-02-19 19:25:26 UTC
# updated       : 2026-03-27 23:31:49 UTC
# description   : Tmux configuration.

set -g default-terminal "screen-256color"

# -------------------- ( history ) 

set-option -g history-limit 1000000

# -------------------- ( mouse ) 

# set -g mouse on

# -------------------- ( status bar )  

set -g status-bg '#777777'
set -g status-fg '#FFFFFF'

# --------------------( vim mode ) 

# set-window-option mode-keys vi
