#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/cyberchef]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-01 19:55:12 UTC
# :updated       : 2024-09-15 12:47:08 UTC
# :description   : Run CyberChef as a Docker container.

# :/Cyberchef is a simple, intuitive web app for analysing and decoding data
# : without having to deal with complex tools or programming languages.
# : CyberChef encourages both technical and non-technical people to explore
# : data formats, encryption and compression.

cyberchef() {

    if [[ $(command systemctl is-active docker.service) == 'inactive' ]]; then
        sudo systemctl start docker.service
        echo "[-] Starting docker.service ..."
    fi

    if [[ "${1}" == 'stop' ]]; then
        echo "================================================================================"
        echo "[+] cyberschef()"
        echo "    Stoping CyberChef Docker container."
        echo "================================================================================"
        echo


        command docker stop $(command docker ps \
                              | command grep "mpepping/cyberchef" \
                              | command cut -d ' ' -f1)
        
        echo "[!] Done."
        sleep 1
    else
        echo "================================================================================"
        echo "[+] cyberschef()"
        echo "    Starting CyberChef Docker container."
        echo "================================================================================"
        echo

        echo "[!] Use <cyberchef stop> when you are done."
        sleep 2

        if command docker ps --all | command grep -q "mpepping/cyberchef"; then
            $BROWSER "http://localhost:8888"
        else
            command docker run --rm -d -p 8888:8000 mpepping/cyberchef \
            && $BROWSER "http://localhost:8888"
        fi
    fi
    }
