#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/deep-map]
# :author        : fantomH @alterEGO Linux
# :created       : 2021-03-19 09:37:19 UTC
# :updated       : 2024-08-29 11:13:13 UTC
# :description   : Complete Nmap scan.

deep-nmap() {

    message action "deep-nmap"
    message result "Running `sudo grc nmap -sV -O -sC --traceroute`"
    message alert "Scanning multiple devices or network will take forever..."

    sleep 2
    sudo grc nmap -sV -O -sC --traceroute ${@}
    }
