#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/delete]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-01 19:59:45 UTC
# :updated       : 2024-09-04 10:25:31 UTC
# :description   : Delete directory.

delete() {

    echo "================================================================================"
    echo "[+] delete()"
    echo "    Running <rm --recursive --force \"${1}\">"
    echo "================================================================================"
    echo

    if [ -d "${1}" ]; then
        read -p "[?] Are you sure your want to delete this directory? [y/N] " INPUT
            if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                rm --recursive --force "${1}" 
            else
                echo "[!] OK... Abording deletion!"
            fi
    else
        echo "[!] There is nothing to do here!"
    fi
  }
