#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/directory-size]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-01 20:01:01 UTC
# :updated       : 2024-09-04 09:49:48 UTC
# :description   : Check size of biggest directories.

directory-size() {

    echo "================================================================================"
    echo "[+] directory-size()"
    echo "    Checking size of biggest directories."
    echo "================================================================================"
    echo

    echo "[-] Size of current directory, followed by biggest child directories:"

    du --bytes --human-readable --max-depth 1 2> /dev/null                    \
    | sort --reverse --human-numeric-sort                                     \
    | head

  }
