#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/getmp3]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:36:18 UTC
# :updated       : 2024-09-04 08:53:52 UTC
# :description   : Extract video audio to .mp3.

getmp3() {

    echo "================================================================================"
    echo "[+] getmp3()"
    echo "    Running <yt-dlp -x --audio-format mp3 --prefer-ffmpeg 'url'>"
    echo "    Extracting video audio to .mp3:"
    echo "    ${1}"
    echo "================================================================================"
    echo

    yt-dlp -x --audio-format mp3 --prefer-ffmpeg "${1}"

  }
