#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/history-cleaner]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:44:35 UTC
# :updated       : 2024-09-16 11:19:21 UTC
# :description   : Cleans bash history.

history-cleaner() {

    echo "================================================================================"
    echo "[+] history-cleaner()"
    echo "    Cleans bash history."
    echo "================================================================================"
    echo

    dumpfile="/tmp/history-cleaner.dump"
    tempfile="/tmp/history-cleaner.temp"

    if [[ ${@} == '' ]]; then
        # :Uses `fzf` to sort through the bash history and let you delete an entry.
        choices=$(history | command fzf --multi --tac)

        if [[ -z "${choices}" ]]; then
            echo "[!] Nothing was selected."
        else
            echo "[-] Candidate(s) for deletion:"
            for c in "${choices}"; do
                echo "${c}"
            done
            read -p "[?] Are you sure your want to delete these? [y/N] " INPUT
                if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                    to_delete=($(command awk '{ print $1 }' <<< "${choices}" | command sort -nr))
                    for c in "${to_delete[@]}"; do
                        history -d ${c}
                    done
                fi
        fi

    elif [[ ${@} == '--editor' ]]; then
        editors=(vim code)
        for editor in "${editors[@]}"; do
            if editor_path=$(command -v "${editor}"); then
                editor=${editor}
                break
            fi
        done

        history -a
        history > ${dumpfile}
        ${editor} ${dumpfile}
        read -p "[?] Are you sure your want to commit the changes? [y/N] " INPUT
            if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                command sort -n ${dumpfile} > ${tempfile}
                command sed -E -i 's/^[[:space:]]+?[0-9]+[[:space:]]+//' ${tempfile}
                history -c \
                && history -r ${tempfile} \
                && history -w
                command rm ${dumpfile}
                command rm ${tempfile}
            fi

    else
        history -a
        command cp ${HOME}/.bash_history ${dumpfile}
        if [[ -z $(command sed -E -n "/^${@}$/p" ${dumpfile}) ]]; then
            echo "[!] Nothing was found."
        else
            echo "[-] Candidate(s) for deletion:"
            command sed -E -n "/^${@}$/p" ${dumpfile}
            echo

            read -p "[?] Are you sure your want to commit the changes? [y/N] " INPUT
                if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                    command sed -E -i "/^${@}$/d" ${dumpfile}
                    history -c \
                    && history -r ${dumpfile} \
                    && history -w
                    command rm ${dumpfile}
                fi
            
        fi

    fi
}
