#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/pacman-reset]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-10-20 10:46:22 UTC
# :updated       : 2024-09-10 12:14:01 UTC
# :description   : Re-initialize pacman sync, mirrorlist and keyring.

pacman-reset() {

    echo "================================================================================"
    echo "[+] pacmn-reset()"
    echo "    Re-initializing pacman sync, mirrorlist and keyring."
    echo "================================================================================"
    echo

    sudo $(command -v rm) -rf /var/lib/pacman/sync
    sudo $(command -v curl) -o /etc/pacman.d/mirrorlist 'https://archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4'
    sudo $(command -v sed) -i -e 's/\#Server/Server/g' /etc/pacman.d/mirrorlist
    sudo $(command -v pacman) -Syy --noconfirm archlinux-keyring
  }
