#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/ports]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-04 02:11:08 UTC
# :updated       : 2024-09-16 12:06:54 UTC
# :description   : Displays open ports.

ports() {

    echo "================================================================================"
    echo "[+] ports()"
    echo "    Running <sudo grc netstat -tulanp>"
    echo "    Displays open ports."
    echo "================================================================================"
    echo

  sudo grc netstat -tulanp
  }
