#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/processes]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:51:54 UTC
# :updated       : 2024-08-30 04:20:59 UTC
# :description   : Show processes.

processes() {

    echo "================================================================================"
    echo "[+] processes()"
    echo "    Running <ps aux>.
    echo "    Show processes."
    echo "================================================================================"
    echo

    ps aux
  }
