#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/shell-info]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 01:18:13 UTC
# :updated       : 2024-09-01 03:05:22 UTC
# :description   : Show shell info.

shell-info() {

    # :Could build something with fzf to search and give info.
    # :ref. https://stackoverflow.com/a/949006/10500496
    # :You can use the bash(1) built-in compgen
    # :    compgen -c will list all the commands you could run.
    # :    compgen -a will list all the aliases you could run.
    # :    compgen -b will list all the built-ins you could run.
    # :    compgen -k will list all the keywords you could run.
    # :    compgen -A function will list all the functions you could run.
    # :    compgen -A function -abck will list all the above in one go.

    echo "================================================================================"
    echo "[+] shell-info()"
    echo "    Show shell info for ${@}."
    echo "================================================================================"
    echo

    shopt -s extdebug
    type -a ${@}
    declare -F ${@}
  }
