#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/show-utc]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 01:36:14 UTC
# :updated       : 2024-09-01 02:57:25 UTC
# :description   : Show UTC time.

show-utc() {

    echo "================================================================================"
    echo "[+] show-utc()"
    echo "    Show UTC time."
    echo "================================================================================"
    echo

    echo  $(date --utc "+%F %H:%M:%S %Z")
  }
