#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/systeminfo]
# :author        : fantomH @alterEGO Linux
# :created       : 2024-09-06 02:46:36 UTC
# :updated       : 2024-09-12 18:24:26 UTC
# :description   : Display system info.

systeminfo() {

    echo "================================================================================"
    echo "[+] systeminfo()"
    echo "    Display system info."
    echo "================================================================================"
    echo

    # :---/ IP ADDRESSES /---:

    echo "[-] IP ADDRESSES"
    echo "--------------------------------------------------------------------------------"
    echo
    command ip -4 a                                                           \
    | command awk '/inet/ {print "   ",$2" ("$NF")"}'

    echo -e "    "$(host myip.opendns.com resolver1.opendns.com               \
                | command grep --color=never -oP '(?<=myip.opendns.com has address ).*$')" (PUBLIC)"
    echo

    # :---/ DOCKER /---:

    if [[ -n $(command -v docker) ]]; then
        echo "[-] RUNNING DOCKERS"
        echo "--------------------------------------------------------------------------------"
        echo
        if [[ -n $(command docker ps -q) ]]; then
            command docker inspect $(command docker ps -q) | command jq -r '
        .[] |
        "\(.Name)
    IP Address     : \(
        .NetworkSettings.Ports | 
        to_entries[] |
        select(.key | contains("tcp")) |
        .value[0] |
        select(.HostPort != null) |
        "\(.HostIp):\(.HostPort)")
    Container ID   : \(.Id)
    MAC Address    : \(.NetworkSettings.Networks[].MacAddress)
    PID            : \(.State.Pid)
    IP Address alt : \(.NetworkSettings.Networks[].IPAddress)\n"'
        else
            echo "[!] No docker container running..."
        fi
    else
        echo "[-] RUNNING DOCKERS"
        echo "--------------------------------------------------------------------------------"
        echo
        echo "[!] Docker not installed."
    fi

  }
