#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/termbin]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-11-26 17:45:44 UTC
# :updated       : 2024-09-01 04:10:26 UTC
# :description   : Netcat-based command-line pastebin.

  # :url: https://termbin.com/
  # :usage `echo just testing! | termbin`

  alias termbin="nc termbin.com 9999"
