#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/scripts/translate]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:56:31 UTC
# :updated       : 2024-08-31 01:05:32 UTC
# :description   : Translate using Google translate.

translate() {

    echo "================================================================================"
    echo "[+] translate()"
    echo "    Usage: tranlate <work> or <\"Sentence\"> <language code>"
    echo "    Using Google translate."
    echo "================================================================================"
    echo

    echo "Original: ${1}"
    TRANSLATION=$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${2}&dt=t&q=${1}" | awk -F '"' '{print $2}' | head -n 1)
    echo "Translation (${2}): "${TRANSLATION}""
  }
