#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/busy]
# :author        : alterEGO Linux
# :created       : 2023-08-01 19:55:12 UTC
# :updated       : 2025-02-25 11:34:54 UTC
# :description   : When the boss comes around to look busy.

busy() {

    # :(ref) https://www.commandlinefu.com/commands/view/6663/pretend-to-be-busy-in-office-to-enjoy-a-cup-of-coffee
    # :CTRL+c to quit.

    command cat /dev/urandom \
    | command hexdump -C \
    | command grep --color=always 'ca fe'
    }
