#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/cyberchef]
# :author        : AlterEGO Linux
# :created       : 2023-08-01 19:55:12 UTC
# :updated       : 2025-02-27 12:05:43 UTC
# :description   : Run CyberChef as a Docker container.


cyberchef() {

    local SERVICE_NAME="docker.service"
    local CONTAINER_IMAGE="mpepping/cyberchef"
    local CONTAINER_NAME="CYBERCHEF"

    if [[ $(command systemctl is-active "$SERVICE_NAME") == "inactive" ]]; then
        sudo systemctl start "$SERVICE_NAME"
    fi

    # :-( help )
    if [[ "$1" == "-h" || "$1" == "--help" || "$1" == "" ]]; then
        echo "================================================================================"
        echo "[+] CyberChef Docker Wrapper"
        echo "================================================================================"
        echo "Usage: cyberchef [start|stop|-h|--help]"
        echo
        echo "  Cyberchef is a simple, intuitive web app for analysing and decoding data"
        echo "  without having to deal with complex tools or programming languages."
        echo "  CyberChef encourages both technical and non-technical people to explore"
        echo "  data formats, encryption and compression."
        echo
        echo "  start  - Launch the CyberChef container (default if no argument is provided)."
        echo "  stop   - Stop the running CyberChef container."
        echo "  -h, --help  - Display this help message."
        echo
        echo "[!] Use <cyberchef stop> when you are done."
        echo "================================================================================"
        return 0
    fi

    # :-( start )
    if [[ "$1" == "start" ]]; then
        echo "================================================================================"
        echo "[+] cyberchef - Starting CyberChef Docker container."
        echo "================================================================================"

        echo "[!] Use <cyberchef stop> when you are done."
        sleep 2

        # :Check if the container already exists.
        if command docker ps --all | grep -q "$CONTAINER_NAME"; then
            # :Container exists: start.
            command docker start "$CONTAINER_NAME"
        else
            # :Container does not exist
            command docker run --name "$CONTAINER_NAME" --rm -d -p 8888:8000 "$CONTAINER_IMAGE" &
        fi

        # :Wait for the container to appear in `docker ps -a`.
        while ! command docker ps --all | grep -q "$CONTAINER_NAME" 2>/dev/null; do
            sleep 1
        done

        # :Wait for the container to be fully up and running.
        while [ "$(docker inspect -f '{{.State.Running}}' "$CONTAINER_NAME")" != "true" 2>/dev/null ]; do
            sleep 1
        done
        sleep 2

        # :Open in browser.
        $BROWSER "http://localhost:8888"

        return 0
    fi

    # :-( stop )
    if [[ "$1" == "stop" ]]; then
        echo "================================================================================"
        echo "[+] cyberchef - Stopping CyberChef Docker container."
        echo "================================================================================"

        local CONTAINER_ID
        CONTAINER_ID=$(docker ps | grep "$CONTAINER_NAME" | awk '{print $1}')

        if [[ -n "$CONTAINER_ID" ]]; then
            command docker stop "$CONTAINER_ID"
            echo "[!] CyberChef container stopped."
        else
            echo "[!] No running CyberChef container found."
        fi
        return 0
    fi
}
