#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/deep-scan]
# :author        : AlterEGO Linux
# :created       : 2023-10-20 09:10:13 UTC
# :updated       : 2025-02-27 11:27:39 UTC
# :description   : Scans IP with rustscan and nmap.

deep-scan() {

    if [[ $# -eq 0 ]]; then
        set -- "-h"
    fi

    for arg in "$@"; do
        if [[ "$arg" == "-h" || "$arg" == "--help" ]]; then
            echo "================================================================================"
            echo "[+] deep-scan - RustScan Wrapper"
            echo "================================================================================"
            echo "Usage: deep-scan <Target> | [-h|--help]"
            echo
            echo "  Runs RustScan as sudo with the following options:"
            echo "    --ulimit 5000       - Increase file descriptor limit."
            echo "    --batch-size 2000   - Adjust batch scanning size."
            echo "    -sV                 - Detect service versions."
            echo "    -O                  - Enable OS detection."
            echo "    -sC                 - Run Nmap's default scripts."
            echo "    --traceroute        - Perform a traceroute."
            echo "    -Pn                 - Treat all hosts as online."
            echo
            echo "Options:"
            echo "  -h, --help    - Display this help message."
            echo
            echo "Examples:"
            echo "  deep-scan 192.168.1.1"
            echo "  deep-scan localhost"
            echo "================================================================================"
            return 0
        fi
    done

    if [[ "$1" == "localhost" ]]; then
        IP="127.0.0.1"
    else
        IP="$1"
    fi

    echo "================================================================================"
    echo "[+] deep-scan - Running: sudo rustscan -a ${IP} --ulimit 5000 --batch-size 2000 -- -sV -O -sC --traceroute -Pn"
    echo "================================================================================"
    echo

    sudo rustscan -a "$IP" --ulimit 5000 --batch-size 2000 -- -sV -O -sC --traceroute -Pn
}
