#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [/shellutils/deep-scan]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-10-20 09:10:13 UTC
# updated       : 2026-01-03 23:36:39 UTC
# description   : Scans IP with rustscan and nmap.

[ -n "${__SOURCED_DEEP_SCAN:-}" ] && return
__SOURCED_DEEP_SCAN=1

deep-scan() {

    # --- shell clean up.
    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'

    trap 'unset -f check_applications usage; trap - RETURN' RETURN

    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications rustscan sudo nmap || return 1

    usage() {
        cat <<EOF
================================================================================
[+] deep-scan - Scans IP with rustscan and nmap.
================================================================================
Usage: deep-scan <Target> | [-h|--help]

Runs RustScan to find the available ports and passes the ports to Nmap.

Options:
  -h, --help    Display this help message.

Examples:
  deep-scan 192.168.1.1
  deep-scan localhost
================================================================================
EOF
    }

    # --- setting IP value.
    local IP
    IP="${1:-127.0.0.1}"
    [[ "$IP" == "localhost" ]] && IP="127.0.0.1"

    # --- show help and ignore other arguments.
    local i
    for i in "${@}"; do
        if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
            usage
            return 0
        fi
    done

    # --- too many arguments.
    if [[ $# -gt 1 ]]; then
        printf '%s\n' "${RED}[!]${RESET} Too many arguments."
        usage
        return 1
    fi

    # --- rustscan.
    printf '%s\n' "${BLUE}[+]${RESET} Running Rustscan to find open ports."

    local PORTS=$(rustscan -a "$IP" --ulimit 5000 --batch-size 2000 --greppable | grep -oP '\[\K[0-9,]+(?=\])')

    # --- nmap.
    if [[ -n "${PORTS}" ]]; then
        printf '%s\n' "${BLUE}[-]${RESET} Found ${PORTS}."
        printf '%s\n' "${BLUE}[+]${RESET} Running Nmap."

        # --- check grc availability.
        local NMAP
        if command -v grc >/dev/null 2>&1; then
            NMAP=(grc nmap)
        else
            NMAP=(nmap)
        fi 

        sudo "${NMAP[@]}" -sV -O -sC --traceroute "${IP}" -p "${PORTS}"
        return 0
    else
        printf '%s\n' "${RED}[!]${RESET} Found nothing."
        return 1
    fi
}
