#!/usr/bin/env bash
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/deep-nmap]
# :author        : AlterEGO Linux
# :created       : 2021-03-19 09:37:19 UTC
# :updated       : 2025-08-14 11:12:55 UTC
# :description   : Deep Nmap scan.

deep-nmap() {

    local ARGUMENTS_INPUT=("${@}")

    # :: Unsetting functions to clean shell.
    unsetter() {
        unset -f usage
        unset -f unsetter
    }

    # :: help / usage / documentation.
    usage() {
        cat <<EOF
================================================================================
[+] deep-nmap - Deep Nmap scan.
================================================================================
Usage: deep-nmap <Target> [Nmap Options] | [-h|--help]

Runs Nmap as sudo with customizable arguments. Defaults to:
  -sV          - Detect service versions.
  -O           - Enable OS detection.
  -sC          - Run Nmap's default scripts.
  --traceroute - Perform a traceroute to the target.

Options:
  -h, --help    - Display this help message.

Examples:
  deep-nmap 192.168.1.1
  deep-nmap scanme.nmap.org --Pn
================================================================================
EOF
    }

    # :: No arguments.
    if [[ $# == 0 ]]; then
        ARGUMENTS_INPUT=("-h")
    fi

    # :: Show help and ignore other arguments.
    local i
    for i in "${ARGUMENTS_INPUT[@]}"; do
        if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
            usage
            unsetter
            return 0
        fi
    done

    sudo grc nmap -sV -O -sC --traceroute "$@"
    unsetter
    return 0
}
