#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [shellutils/deep-scan]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-10-20 09:10:13 UTC
# updated       : 2025-12-22 02:09:58 UTC
# description   : Scans IP with rustscan and nmap.

deep-scan() {

    # --- shell clean up.
    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'
    local IP
    local NMAP
    local PORTS

    trap 'unset -f check_applications usage; trap - RETURN' RETURN

    check_applications() {
        # --- verify applications on system.

        local app
        local apps=("$@")
        local missing=()

        for app in "${apps[@]}"; do
            if ! command -v "${app}" > /dev/null 2>&1; then
                missing+=("${app}")
            fi
        done

        if (( ${#missing[@]} > 0 )); then
            printf '%s\n' "${RED}[!]${RESET} Missing application(s): ${missing[*]}."
            return 1
        fi
    }

    usage() {
        cat <<EOF
================================================================================
[+] deep-scan - Scans IP with rustscan and nmap.
================================================================================
Usage: deep-scan <Target> | [-h|--help]

Runs RustScan to find the available ports and passes the ports to Nmap.

Options:
  -h, --help    Display this help message.

Examples:
  deep-scan 192.168.1.1
  deep-scan localhost
================================================================================
EOF
    }

    # --- check applications.
    if ! check_applications rustscan nmap sudo; then
        return 1
    fi

    # --- setting IP value.
    IP="${1:-127.0.0.1}"
    [[ "$IP" == "localhost" ]] && IP="127.0.0.1"

    # --- show help and ignore other arguments.
    local i
    for i in "${@}"; do
        if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
            usage
            return 0
        fi
    done

    # --- too many arguments.
    if [[ $# -gt 1 ]]; then
        printf '%s\n' "${RED}[!]${RESET} Too many arguments."
        usage
        return 1
    fi

    # --- rustscan.
    printf '%s\n' "${BLUE}[+]${RESET} Running Rustscan to find open ports."

    PORTS=$(rustscan -a "$IP" --ulimit 5000 --batch-size 2000 --greppable | grep -oP '\[\K[0-9,]+(?=\])')

    # --- nmap.
    if [[ -n "${PORTS}" ]]; then
        printf '%s\n' "${BLUE}[-]${RESET} Found ${PORTS}."
        printf '%s\n' "${BLUE}[+]${RESET} Running Nmap."

        # --- check grc availability.
        if command -v grc >/dev/null 2>&1; then
            NMAP=(grc nmap)
        else
            NMAP=(nmap)
        fi 

        sudo "${NMAP[@]}" -sV -O -sC --traceroute "${IP}" -p "${PORTS}"
        return 0
    else
        printf '%s\n' "${RED}[!]${RESET} Found nothing."
        return 1
    fi
}
