#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [shellutils/deep-nmap]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2025-12-22 02:05:30 UTC
# updated       : 2025-12-22 02:05:30 UTC
# description   : Deep Nmap scan.

deep-nmap() {

    # --- ( shell clean up )
    local ARGUMENTS_INPUT=("${@}")

    trap '
        unset -f usage; trap - RETURN' RETURN

    # --- ( help )
    usage() {
        cat <<EOF
================================================================================
[+] deep-nmap - Deep Nmap scan.
================================================================================
Usage: deep-nmap <Target> [Nmap Options] | [-h|--help]

Runs Nmap as sudo with customizable arguments. Defaults to:
  -sV          - Detect service versions.
  -O           - Enable OS detection.
  -sC          - Run Nmap's default scripts.
  --traceroute - Perform a traceroute to the target.

Options:
  -h, --help    - Display this help message.

Examples:
  deep-nmap 192.168.1.1
  deep-nmap scanme.nmap.org --Pn
================================================================================
EOF
    }

    # --- no arguments.
    if [[ $# == 0 ]]; then
        ARGUMENTS_INPUT=("-h")
    fi

    # --- show help and ignore other arguments.
    local i
    for i in "${ARGUMENTS_INPUT[@]}"; do
        if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
            usage
            return 0
        fi
    done

    sudo grc nmap -sV -O -sC --traceroute "$@"
    return 0
}
