#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/delete]
# :author        : AlterEGO Linux
# :created       : 2023-08-01 19:59:45 UTC
# :updated       : 2025-02-27 11:34:53 UTC
# :description   : Delete directory.

delete() {

    if [ -d "${1}" ]; then
        read -p "[?] Are you sure your want to delete this directory? [y/N] " INPUT
            if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                command rm --recursive --force "${1}" 
            else
                echo "[!] OK... Abording deletion!"
            fi
    else
        echo "[!] There is nothing to do here!"
    fi
  }
