#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/directory-size]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-01 20:01:01 UTC
# :updated       : 2024-09-16 10:20:02 UTC
# :description   : Check size of biggest directories.

directory-size() {

    echo "================================================================================"
    echo "[+] directory-size()"
    echo "    Checking size of biggest directories."
    echo "================================================================================"
    echo

    echo "[-] Size of current directory, followed by biggest child directories:"

    command du --bytes --human-readable --max-depth 1 2> /dev/null \
    | command sort --reverse --human-numeric-sort \
    | command head

  }
