#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [shellutils/directory-size]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-01 20:01:01 UTC
# updated       : 2025-12-22 02:20:50 UTC
# description   : Check size of biggest directories.

directory-size() {

    local BLUE=$'\033[34m'
    local RESET=$'\033[0m'

    printf '%s\n' "${BLUE}[+]${RESET} Size of current directory, followed by biggest child directories:"

    command du --bytes --human-readable --max-depth 1 2> /dev/null \
    | command sort --reverse --human-numeric-sort \
    | command head
}
