#!/usr/bin/env bash
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/directory-size]
# :author        : AlterEGO Linux
# :created       : 2023-08-01 20:01:01 UTC
# :updated       : 2025-08-15 11:06:43 UTC
# :description   : Check size of biggest directories.

directory-size() {

    local BLUE=$'\033[34m'
    local RESET=$'\033[0m'

    printf '%s\n' "${BLUE}[+]${RESET} Size of current directory, followed by biggest child directories:"

    command du --bytes --human-readable --max-depth 1 2> /dev/null \
    | command sort --reverse --human-numeric-sort \
    | command head
}
