#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [/shellutils/elevate]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 00:10:38 UTC
# updated       : 2025-12-29 00:39:06 UTC
# description   : Repeats last command with sudo, if forgotten.

[ -n "${__SOURCED_ELEVATE:-}" ] && return
__SOURCED_ELEVATE=1

elevate() {

    # --- shell clean up
    local __args=("${@}")
    local __arg
    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'

    trap 'unset -f usage check_applications; trap - RETURN' RETURN

    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications bash sudo || return 1

    usage() {
        cat <<EOF
================================================================================
[+] elevate - Repeats last command with sudo, if forgotten.
================================================================================
Usage: elevate [--help]

The shellutil <elevate> runs sudo \$(history -p !!), which allows to run the
last command with elevated privileges.

Options:
  -h, --help           Display this help message.
  -i, --interactive    Prompt for confirmation.
================================================================================
EOF
    }

    local __command=$(history -p !!)

    # --- help
    for __arg in "${__args[@]}"; do
        if [ "${__arg}" == '-h' ] || [ "${__arg}" == '--help' ]; then
            usage
            return 0
        fi
    done

    local __input
    for __arg in "${__args[@]}"; do
        if [[ "${__arg}" == '-i' ]] || [[ "${__arg}" == '--interactive' ]]; then
            read -p "${BLUE}[?]${RESET} Are you sure you want to proceed? [y/N] " __input
                if [[ "${__input}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
                    sudo bash -c "${__command}"
                    return 0
                else
                    printf '%s\n' "${RED}[!]${RESET} Aborting running '${__command}' with elevated privileges."
                    return 1
                fi
        fi
    done

    sudo bash -c "${__command}"
}
