#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [shellutils/extractor]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-01 19:55:12 UTC
# updated       : 2025-12-22 04:23:05 UTC
# description   : Compressed files universal extractor.

extractor() {
    command bash ~/.ael/bin/extractor.sh "${@}"
}
