#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/fixout]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:07:03 UTC
# :updated       : 2024-09-16 10:39:03 UTC
# :description   : Fix bash history and exit.

# :/Don't try to put this code in a shell script, it won't work.
# : `history` don't play well in scripts.

fixout() {

    echo "================================================================================"
    echo "[+] fixout()"
    echo "    Cleaning history before closing ..."
    echo "================================================================================"
    echo

    sleep 2

    history -n && history \
    | command sort -k2 -k1nr \
    | command uniq -f1 \
    | command sort -n \
    | command cut -c8- > ~/.tmp$$ \
    && history -c \
    && history -r ~/.tmp$$ \
    && history -w \
    && command rm ~/.tmp$$ \
    && exit
  }
