#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/fuck]
# :author        : AlterEGO Linux
# :created       : 2023-08-02 00:10:38 UTC
# :updated       : 2025-03-02 15:01:27 UTC
# :description   : Repeats last cmd with sudo if forgotten.

fuck() {

    echo "================================================================================"
    echo "[+] f**k - Repeats last cmd with sudo if forgotten."
    echo "================================================================================"
    echo

    COMMAND=$(history -p !!)
    echo "[!] You will be running:"
    echo
    echo "    sudo ${COMMAND}"
    echo
    read -p "[?] Are you sure you want to proceed? [y/N] " INPUT
        
        if [[ "${INPUT}" =~ ^([yY][eE][sS]|[yY])$ ]]; then
            sudo bash -c "${COMMAND}"
        fi
}
