#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [/shellutils/ispeed]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2024-05-16 14:54:18 UTC
# updated       : 2026-01-04 00:24:56 UTC
# description   : Internet connection speed meter.

[ -n "${__SOURCED_ISPEED:-}" ] && return
__SOURCED_ISPEED=1



ispeed() {

    local ARGUMENTS_INPUT=("${@}")
    local selection

    trap 'unset -f run_method usage use_fzf; trap - RETURN' RETURN

    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }

    usage() {
      cat <<EOF
================================================================================
[+] ispeed - Calculate Internet connection speed.
================================================================================
Usage: ispeed [--fzf|--web METHOD|--cli METHOD|--git METHOD|--help]

ispeed offers different ways to calculate your Internet speed.

--fzf       Uses fzf to display and select a method.
--cli       Uses a local application. Requires a METHOD.
--git       Uses git, curl, wget etc. to run command.
            Requires a METHOD.
--web       Uses default browser. Requires a METHOD.

methods:
    - (cli) speedtest
            Uses the speedtest-cli package.
    - (git) speedtest
            Uses curl and python.
            URL: https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
    - (web) speedtest
            URL: https://www.speedtest.net/
    - (web) Fast.com
            URL: https://fast.com
    - (web) speedof.me
            URL: https://speedof.me/

================================================================================
EOF
    }

    use_fzf() {

        if [[ -n ${__SOURCED_AEL_FZF} ]]; then
            selection=$(printf "%s\n" "${methods[@]}" | ael-fzf -p "iSPEED methods")
        else
            selection=$(printf "%s\n" "${methods[@]}" | fzf --prompt "iSPEED methods")
        fi
        
    }

    run_method() {
        if [[ -n "${selection}" ]]; then
            echo "[-] ispeed - Using $selection"
            echo
            if [[ "${selection}" == "(cli) speedtest" ]]; then
                check_applications speedtest || return 1
                command speedtest --secure
            elif [[ "${selection}" == "(git) speedtest" ]]; then
                check_applications curl python || return 1
                    command curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py \
                    | command python - --secure
            elif [[ "${selection}" == "(web) speedtest" ]]; then
                ${browser} "https://www.speedtest.net/"
            elif [[ "${selection}" == "(web) Fast.com" ]]; then
                ${browser} "https://fast.com"
            elif [[ "${selection}" == "(web) speedof.me" ]]; then
                ${browser} "https://speedof.me/"
            fi
        else
            echo "[!] ispeed - Aborting..."
        fi
    }

    local methods
    methods=("(cli) speedtest"
             "(git) speedtest"
             "(web) speedtest"
             "(web) Fast.com"
             "(web) speedof.me")

    local browser="${BROWSER:-xdg-open}"

    # --- no arguments.
    if [[ $# == 0 ]]; then
        check_applications fzf || return 1
        use_fzf
        run_method
        return 0
    fi

    # --- show help and ignore other arguments.
    local i
    for i in "${ARGUMENTS_INPUT[@]}"; do
        if [[ "${i}" == "-h" || "${i}" == "--help" ]]; then
            usage
            return 0
        fi
    done

    # --- arguments parser.
    for i in "${!ARGUMENTS_INPUT[@]}"; do
        if [[ "${ARGUMENTS_INPUT[i]}" == "--fzf" ]]; then
            check_applications fzf || return 1
            use_fzf
            run_method
            return 0
        elif [[ "${ARGUMENTS_INPUT[i]}" == "--cli" ]]; then
            if [[ -n "${ARGUMENTS_INPUT[i+1]}" && "${ARGUMENTS_INPUT[i+1]}" == "speedtest" ]]; then
                selection="(cli) speedtest"
                run_method
                return 0
            else
                usage
                echo
                echo "[!] --cli requires a valid argument."
                return 1
            fi
        elif [[ "${ARGUMENTS_INPUT[i]}" == "--git" ]]; then
            if [[ -n "${ARGUMENTS_INPUT[i+1]}" && "${ARGUMENTS_INPUT[i+1]}" == "speedtest" ]]; then
                selection="(git) speedtest"
                run_method
                return 0
            else
                usage
                echo
                echo "[!] --git requires a valid argument."
                return 1
            fi

        elif [[ "${ARGUMENTS_INPUT[i]}" == "--web" ]]; then
            if [[ -n "${ARGUMENTS_INPUT[i+1]}" ]]; then
                if [[ "${ARGUMENTS_INPUT[i+1]}" == "speedtest" ]]; then
                    selection="(web) speedtest"
                    run_method
                    return 0
                elif [[ "${ARGUMENTS_INPUT[i+1]}" == "Fast.com" ]]; then
                    selection="(web) Fast.com"
                    run_method
                    return 0
                elif [[ "${ARGUMENTS_INPUT[i+1]}" == "speedof.me" ]]; then
                    selection="(web) speedof.me"
                    run_method
                    return 0
                else
                    usage
                    echo
                    echo "[!] --web requires a valid argument."
                    return 1
                fi
            else
                usage
                echo
                echo "[!] --web requires a valid argument."
                return 1
            fi
        fi
    done

    # --- garbage argument collector.
    usage
    echo
    echo "[!] No valid arguments found."
    return 1
}
