#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/pacman-reset]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-10-20 10:46:22 UTC
# updated       : 2026-01-04 01:51:30 UTC
# description   : Re-initialize pacman sync, mirrorlist and keyring.


[ -n "${__SOURCED_PACMAN_RESET:-}" ] && return
__SOURCED_PACMAN_RESET=1

pacman-reset() {

    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'
    
    trap 'unset -f check_applications; trap - RETURN' RETURN
        
    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications curl sudo pacman sed || return 1

    printf '%s\n' "${BLUE}[+]${RESET} pacmn-reset - Re-initializing Pacman."

    printf '%s\n' "${BLUE}[-]${RESET} Removing sync file."
    sudo $(command -v rm) -rf /var/lib/pacman/sync

    printf '%s\n' "${BLUE}[-]${RESET} Fetching Pacman mirrorlist."
    sudo $(command -v curl) -o /etc/pacman.d/mirrorlist 'https://archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4'

    printf '%s\n' "${BLUE}[-]${RESET} Fixing Pacman mirrorlist."
    sudo $(command -v sed) -i -e 's/\#Server/Server/g' /etc/pacman.d/mirrorlist

    printf '%s\n' "${BLUE}[-]${RESET} Updating archlinux-keyring."
    sudo $(command -v pacman) -Syy --noconfirm archlinux-keyring

    printf '%s\n' "${BLUE}[-]${RESET} All done!"
}
