#!/usr/bin/env bash
# :: --------------------------------------------------------------------- INFO
# :: [~/.ael/shellutils/pacman-reset]
# :: author        : AlterEGO Linux
# :: created       : 2023-10-20 10:46:22 UTC
# :: updated       : 2025-08-15 16:26:23 UTC
# :: description   : Re-initialize pacman sync, mirrorlist and keyring.

pacman-reset() {

    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'

    printf '%s\n' "${BLUE}[+]${RESET} pacmn-reset - Re-initializing Pacman."

    printf '%s\n' "${BLUE}[-]${RESET} Removing sync file."
    sudo $(command -v rm) -rf /var/lib/pacman/sync

    printf '%s\n' "${BLUE}[-]${RESET} Fetching Pacman mirrorlist."
    sudo $(command -v curl) -o /etc/pacman.d/mirrorlist 'https://archlinux.org/mirrorlist/?country=US&protocol=http&protocol=https&ip_version=4'

    printf '%s\n' "${BLUE}[-]${RESET} Fixing Pacman mirrorlist."
    sudo $(command -v sed) -i -e 's/\#Server/Server/g' /etc/pacman.d/mirrorlist

    printf '%s\n' "${BLUE}[-]${RESET} Updating archlinux-keyring."
    sudo $(command -v pacman) -Syy --noconfirm archlinux-keyring

    printf '%s\n' "${BLUE}[-]${RESET} All done!"
}
