#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/ports]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-04 02:11:08 UTC
# updated       : 2026-01-05 02:26:02 UTC
# description   : Displays open ports.

ports() {
    
    [ -n "${__SOURCED_PORTS:-}" ] && return
    __SOURCED_PORTS=1

    trap 'unset -f check_applications; trap - RETURN' RETURN

    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications netstat || return 1

    if [[ $(command -v grc) ]]; then
        sudo grc netstat -tulanp
    else
        sudo netstat -tulanp
    fi
}
