#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/ports]
# :author        : AlterEGO Linux
# :created       : 2023-08-04 02:11:08 UTC
# :updated       : 2025-07-08 17:34:19 UTC
# :description   : Displays open ports.

ports() {

    if [[ $(command -v grc) ]]; then
        sudo grc netstat -tulanp
    else
        sudo netstat -tulanp
    fi
}
