#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/processes]
# :author        : AlterEGO Linux
# :created       : 2023-08-02 00:51:54 UTC
# :updated       : 2025-07-08 18:07:11 UTC
# :description   : Show processes.

processes() {

    if [[ $(command -v grc) ]]; then
        command grc ps aux
    else
        command ps aux
    fi
}
