#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/processes]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 00:51:54 UTC
# updated       : 2026-01-05 02:27:59 UTC
# description   : Show processes.

processes() {
    
    [ -n "${__SOURCED_PROCESSES:-}" ] && return
    __SOURCED_PROCESSES=1
    
    trap 'unset -f check_applications; trap - RETURN' RETURN
    
    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${RED}[!]${RESET} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications ps || return 1

    if [[ $(command -v grc) ]]; then
        command grc ps aux
    else
        command ps aux
    fi
}
