#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/ps-grep]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 00:56:31 UTC
# updated       : 2026-01-05 03:18:18 UTC
# description   : Show processes for a particular application.

ps-grep() {

    local __yellow=$'\033[43m\033[30m'
    local __bold=$'\033[1m'
    local __reset=$'\033[0m'
    local __red=$'\033[31m'

    # --- error handler if no argument provided.
    if [ $# -eq 0 ]; then
        printf '%s\n' "${__red}[!]${__reset} No pattern provided."
        return 1
    fi

    local __pattern="[${1:0:1}]${1:1}"

    # --- get header.
    local __header=$(ps aux | head -n 1)

    # --- get pattern.
    local __matches=$(ps aux | grep -Ei "$__pattern" | grep -Ev "ps-grep|grep")

    # --- error handler if no match found.
    if [ -z "$__matches" ]; then
        printf '%s\n' "${__red}[!]${__reset} No matching process found."
        return 1
    fi

    # --- compare width of terminal and lenght of lines to determine the display.
    local __need_spacing=0
    local __width=$(tput cols)
    local __line

    while IFS= read -r __line; do
        if [ "${#__line}" -ge "$__width" ]; then
            __need_spacing=1
            break
        fi
    done <<< "$__matches"

    # --- Display.

    printf '%s\n' "${__bold}${__header}${__reset}"

    while IFS= read -r __line; do
        local __highlighted
        __highlighted=$(echo "$__line" | GREP_COLORS='mt=43;30' grep --color=always -E "$__pattern|$")
        echo "$__highlighted"
        [ "$__need_spacing" -eq 1 ] && echo
    done <<< "$__matches"
}
