#!/usr/bin/env bash
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/py-cleaner]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 00:59:00 UTC
# updated       : 2026-01-05 09:13:09 UTC
# description   : Clean python current directory.

[ -n "${__SOURCED_PY_CLEANER:-}" ] && return
__SOURCED_PY_CLEANER=1

py-cleaner () {

    # --- ref. <https://stackoverflow.com/a/41386937/10500496>
 
    local __blue=$'\033[34m'
    local __red=$'\033[31m'
    local __reset=$'\033[0m'

    trap 'unset -f check_applications; trap - RETURN' RETURN
    
    check_applications() {
        if [[ -n ${__SOURCED_CHECK_APPLICATIONS} ]]; then
            check-applications "${@}"
        else
            local app
            for app in $@; do
                if ! command -v $app; then
                    printf '%s\n' "${__red}[!]${__reset} ${app} is not installed."
                    return 1
                fi
            done
        fi
    }
    check_applications find || return 1

    printf '%s\n' "${__blue}[+]${__reset} py-cleaner - Cleaning python current directory."

    command find . \( -type f -name '*.py[co]' -o -type d -name __pycache__ \) -delete
}
