#!/usr/bin/env bash
# :: --------------------------------------------------------------------- INFO
# :: [~/.ael/shellutils/py-cleaner]
# :: author        : AlterEGO Linux
# :: created       : 2023-08-02 00:59:00 UTC
# :: updated       : 2025-08-15 16:12:36 UTC
# :: description   : Clean python current directory.

py-cleaner () {

    # :: ref. https://stackoverflow.com/a/41386937/10500496
 
    local BLUE=$'\033[34m'
    local RESET=$'\033[0m'

    printf '%s\n' "${BLUE}[+]${RESET} py-cleaner - Cleaning python current directory."

    command find . \( -type f -name '*.py[co]' -o -type d -name __pycache__ \) -delete
}
