#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/reset-time]
# :author        : AlterEGO Linux
# :created       : 2023-08-02 01:02:11 UTC
# :updated       : 2025-07-08 17:47:30 UTC
# :description   : Reset system time. Useful when Windows boot screws time.

reset-time() {

    local BLUE=$'\033[34m'
    local RED=$'\033[31m'
    local RESET=$'\033[0m'

    printf '%s\n' "${BLUE}[-]${RESET} Time before resetting system: $(date "+%F %H:%M:%S %Z")"

    sudo timedatectl set-ntp true && sudo hwclock --systohc --utc

    printf '%s\n' "${BLUE}[-]${RESET} Time now: $(date "+%F %H:%M:%S %Z")"
}
