#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/search-content]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 01:05:06 UTC
# :updated       : 2024-09-16 15:07:18 UTC
# :description   : Search files for content.

search-content() {

    # :/src/ https://github.com/junegunn/fzf/wiki/Examples#searching-file-contents

    echo "================================================================================"
    echo "[+] search-content()"
    echo "    Search files for content."
    echo "================================================================================"
    echo

    echo "Searching for: ${1}"
    echo
    
    command rg --files-with-matches --no-messages "$1" \
    | command fzf --preview "command highlight -O ansi -l {} 2> /dev/null \
                             | command rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' \
                             || command rg --ignore-case --pretty --context 10 '$1' {}"
  }
