#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/show-utc]
# author        : Pascal Malouin (https://github.com/alterEGO-Linux)
# created       : 2023-08-02 01:36:14 UTC
# updated       : 2026-01-31 22:25:24 UTC
# description   : Show UTC time.

show-utc() {

    echo $(command date --utc "+%F %H:%M:%S %Z")

}
