#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/show-utc]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 01:36:14 UTC
# :updated       : 2025-07-08 16:57:25 UTC
# :description   : Show UTC time.

show-utc() {

    echo $(command date --utc "+%F %H:%M:%S %Z")

}
