#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/show-utc]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 01:36:14 UTC
# updated       : 2026-01-08 02:18:09 UTC
# description   : Show UTC time.

[ -n "${__SOURCED_SHOW_UTC-}" ] && return
__SOURCED_SHOW_UTC=1

show-utc() {

    echo $(command date --utc "+%F %H:%M:%S %Z")

}
