#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/tagalog]
# :author        : fantomH @alterEGO Linux
# :created       : 2023-08-02 00:56:31 UTC
# :updated       : 2024-09-16 17:39:00 UTC
# :description   : Translate to Tagalog using Google translate.

tagalog() {

    echo "================================================================================"
    echo "[+] tagalog()"
    echo "    Usage: tagalog <work> or <\"Sentence\">"
    echo "    Translate to Tagalog using Google translate."
    echo "================================================================================"
    echo

    echo "Original: ${@}"
    TRANSLATION=$(command wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=tl&dt=t&q=${@}" | command awk -F '"' '{print $2}' | command head -n 1)
    echo "Translation to Tagalog: "${TRANSLATION}""
  }
