#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/termbin]
# :author        : AlterEGO Linux
# :created       : 2023-11-26 17:45:44 UTC
# :updated       : 2025-07-12 14:37:07 UTC
# :description   : Netcat-based command-line pastebin.

termbin() {

    local RED=$'\033[31m'
    local RESET=$'\033[0m'

    # :: Verify if any input is provided.
    if [ -t 0 ] && [ $# -eq 0 ]; then
        printf '%s\n' "${RED}[!]${RESET} No input provided. Use: echo 'text' | termbin or termbin \"your text\""
        return 1
    fi

    if [ $# -gt 0 ]; then
        printf '%s\n' "$*"
    else
        cat
    fi | nc termbin.com 9999
}
