#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/tmuxplus]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2020-10-15 17:14:53 UTC
# updated       : 2026-01-08 23:50:36 UTC
# description   : TMUX wrapper.

tmuxplus() {
    command bash ${HOME}/.ael/bin/tmuxplus.sh "${@}"
}
