#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/tmuxplus]
# :author        : fantomH @alterEGO Linux
# :created       : 2020-10-15 17:14:53 UTC
# :updated       : 2024-10-07 18:05:55 UTC
# :description   : TMUX wrapper.

tmuxplus() {


    echo "================================================================================"
    echo "[+] tmuxplus()"
    echo "================================================================================"
    echo

    in_tmux_session() {
        if command env | command grep -q TMUX; then
            return 0
        else
            return 1
        fi
    }

    tmux_access_session() {

        # :/ref/ https://github.com/nwallace/dotfiles/blob/master/scripts/bin/functions

        session="$(command tmux ls -F '#{session_name}' | command fzf)"

        if [[ -n "${session}" ]]; then
            in_tmux_session    
            if [[ $? == "0" ]]; then
                env TERM=screen-256color tmux -u switch-client -t "${session}"
            else
                env TERM=screen-256color tmux -u a -t "${session}"
            fi
        else
            echo "[!] Nothing selected"
        fi
        }

    tmux_background() {

      # :/Send commands to a detached session.

      command tmux new-session -d -s ${session}
      sleep 0.5
      command tmux send-keys -t ${session} "${cmd}" enter
      }

    tmux_wrapper() {

        # :/Generates a random session.

        session=$(echo TEMP${RANDOM})

        env TERM=screen-256color tmux -u new-session -d -s "${session}"
        command tmux send-keys -t "${session}" "${cmd} && exit 0" enter
    }

    tmux_usage() {

        echo "[-] tmuxplus() help"
        echo "    -a | --access Uses fzf to attach or switch to a session."
        echo "    -b | --background Create a detached session and run a command."
        echo "    -w | --wrapper Create a detached session to run a command temporarily."
    }

    case ${1} in

        -a|--access )
            tmux_access_session
            ;;

        -b|--background )
            shift
            session="${1}"
            cmd="${2}"
            tmux_background
            ;;

        -w|--wrapper )
            shift
            cmd="${1}"
            tmux_wrapper
            ;;

        * )
            tmux_usage
            ;;

    esac
}
