#!/usr/bin/env sh
# ------------------------------------------------------------------------ INFO
# [/.ael/shellutils/translate]
# author        : Pascal Malouin @https://github.com/alterEGO-Linux
# created       : 2023-08-02 00:56:31 UTC
# updated       : 2026-01-22 08:23:50 UTC
# description   : Translate using Google translate.

translate() {
      command translate.py "${@}"
  }

# --- as shell script.
#    echo "Original: ${1}"
#    TRANSLATION=$(command wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=${2}&dt=t&q=${1}" | command awk -F '"' '{print $2}' | command head -n 1)
#    echo "Translation (${2}): "${TRANSLATION}""
