#!/usr/bin/env sh
# :----------------------------------------------------------------------- INFO
# :[~/.ael/shellutils/whoisweb]
# :author        : alterEGO Linux
# :created       : 2023-08-01 19:55:12 UTC
# :updated       : 2025-07-07 20:08:14 UTC
# :description   : Query WHOIS web if <whois> port 43 is blocked on your network.

whoisweb() {

    local RED RESET
    RED=$'\033[31m'
    RESET=$'\033[0m'

    if [[ -z "${@}" ]]; then
        printf '%s\n' "${RED}[!]${RESET} You must provide a valid URL."
    else
        command curl --silent https://whoisjs.com/api/v1/${1} \
        | command jq ".raw" \
        | command sed "s/\\\r\\\n/\\n/g"
    fi
}
